name: Portfolio Functionality Tests

on:
  push:
    branches: 
      - main 

  #TODO: Add triggering when cloudflare pages has been deployed
  schedule:
    - cron: '0 0 * * 1'  # Monday at midnight
  # Allow manual triggering
  workflow_dispatch:

jobs:
  test:
    name: Run Functionality Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      
      - name: Install dependencies
        run: |
          yarn install
          yarn install playwright
      
      - name: Install Playwright browser
        run: yarn playwright install chromium --with-deps
      
      - name: Run functionality tests
        run: yarn playwright test
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7